pipeline {
    agent any
    stages {
        stage('Install Dependencies') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install -r requirements.txt'
            }
        }
        stage('Run Script') {
            steps {
                sh './venv/bin/python src/main.py'
            }
        }
        stage('Test') {
            steps {
                sh './venv/bin/pytest'
            }
        }
    }
}
